config/routes.rb
Rails.application.routes.draw do


  get 'comments/create'

  root      'static_pages#home'
  post      '/',              to: 'static_pages#home'
  get       'category',       to: 'static_pages#category'
  post      'category',       to: 'static_pages#category'
  get       'login',          to: 'session#new'
  post      'login',          to: 'session#create'
  get       'logout',         to: 'session#destroy'
  get       'mypage',         to: 'mypage#top'
  post      'mypage',         to: 'mypage#top'
  get       'favourites',     to: 'mypage#favourites'
  post      'favourites',     to: 'mypage#favourites'

  resources :comments
  resources :tips
  resources :users
  resources :relationships,  only: [:create, :destroy]
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new 
    end

    def create
        user = User.find_by(name: params[:session][:name].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to mypage_path
        else
            flash[:danger] = 'Invalid name/password combination'
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
    end

end

app/helpers/session_helper.rb
module SessionHelper
    
    def log_in (user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

end

app/views/session/new.html.erb
<div class="uk-width-1-2">
    <h1>Little Tips For Developer</h1>
</div>

<div class="uk-width-1-2"> 
    <div class="login-form">
        <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "uk-alert uk-alert-#{message_type}") %>
        <% end %>
        <%= form_for(:session, url: login_path) do |f| %>

        <div>
            <%= f.label :name %><br>
            <%= f.text_field :name, class: 'yi-input uk-margin-bottom' %>
        </div>

        <div>
            <%= f.label :password %><br>
            <%= f.password_field :password, class: 'yi-input uk-margin-bottom' %>
        </div>

        <%= f.submit "Log in", class: "uk-button uk-button-primary" %>
        <% end %>

        <h4><%= link_to "Create New User", new_user_path, class: "uk-margin-top" %></h4>
    </div>
</div>