config/routes.rb
Rails.application.routes.draw do


  get 'comments/create'

  root      'static_pages#home'
  post      '/',              to: 'static_pages#home'
  get       'category',       to: 'static_pages#category'
  post      'category',       to: 'static_pages#category'
  get       'login',          to: 'session#new'
  post      'login',          to: 'session#create'
  get       'logout',         to: 'session#destroy'
  get       'mypage',         to: 'mypage#top'
  post      'mypage',         to: 'mypage#top'
  get       'favourites',     to: 'mypage#favourites'
  post      'favourites',     to: 'mypage#favourites'

  resources :comments
  resources :tips
  resources :users
  resources :relationships,  only: [:create, :destroy]
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

    before_action :getBaseInfo2

    def top
        if !login_chk 
            return
        end
        pagenate(Tip.where(user_id: @user.id).order("updated_at desc"), "post")
    end

    def favourites
        if !login_chk 
            return
        end
        pagenate(@user.favourite_tip.order("updated_at desc"), "post")
    end

end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/favourites.html.erb
<div class="uk-width-1-1 user-view">
    <h2 class="user-view-title uk-width-1-1">
        <%= @user.name %>'s Favourite Tips
    </h2>
    <div class="user-view-contents uk-width-1-1" >
        <h3>Name : <%= @user.name %></h3>
        <h3>Your Favourite Tips(<%= @count %>) <%= link_to "Make new Tip", new_tip_path ,:method => :get %></h3>
        <div class="tips-view">
            <%= render 'layouts/tip' %>
        </div>
    </div>
    <%= render 'layouts/pagenate' %>
</div>

app/views/mypage/top.html.erb
<div class="uk-width-1-1 user-view">
    <h2 class="user-view-title uk-width-1-1">
        My Page : <%= @user.name %>
    </h2>
    <div class="user-view-contents uk-width-1-1" >
        <h3>
            Name : <%= @user.name %>
            <span><%= link_to "", edit_user_path(:id => @user.id), :method => :GET, class: "uk-align-right uk-icon-medium uk-icon-edit" %></span>
        </h3>
        <h3>
            Git-URL : 
            <% if @user.giturl %>
                <%= link_to @user.giturl, @user.giturl %>
            <% end %>
        </h3>
        <h3>Your Tips(<%= @count %>) <%= link_to "Make new Tip", new_tip_path ,:method => :get %></h3>
        <div class="tips-view">
            <%= render 'layouts/tip' %>
        </div>
        <div>
            <p class="uk-margin-top" style="color:red; font-size: 0.9em;" >Danger!!:<%= link_to "アカウント削除", @user, method: :delete, data:{ confirm: "一度削除するともとに戻せません。削除しますか？" } %></p>
        </div>
    </div>
    <%= render 'layouts/pagenate' %>
</div>