config/routes.rb
Rails.application.routes.draw do


  get 'comments/create'

  root      'static_pages#home'
  post      '/',              to: 'static_pages#home'
  get       'category',       to: 'static_pages#category'
  post      'category',       to: 'static_pages#category'
  get       'login',          to: 'session#new'
  post      'login',          to: 'session#create'
  get       'logout',         to: 'session#destroy'
  get       'mypage',         to: 'mypage#top'
  post      'mypage',         to: 'mypage#top'
  get       'favourites',     to: 'mypage#favourites'
  post      'favourites',     to: 'mypage#favourites'

  resources :comments
  resources :tips
  resources :users
  resources :relationships,  only: [:create, :destroy]
end

app/models/tip.rb
class Tip < ApplicationRecord
    include SessionHelper
    
    has_many :passive_relationships, class_name:  "Relationship",
                                     foreign_key: "favourite_tip_id",
                                     dependent:   :destroy

    has_many :favouritter, through: :passive_relationships, source: :favouritter
    has_many :comments, dependent: :destroy

    belongs_to :category
    belongs_to :user

    validates :title        ,presence: true
    validates :category_id  ,presence: true
    validates :contents     ,presence: true ,length: { maximum: 1500 }

    def writer?(user_id)
        user.id == user_id
    end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController

    before_action :getBaseInfo

    def show
        @tip = Tip.find(params[:id])
        @current_user = current_user
        @user = User.find_by(id: @tip.user_id)
        @comments = @tip.comments.order("updated_at desc")
    end

    def new
        @tip = Tip.new
        if logged_in?
            render 'new'
        else
            redirect_to '/login'
        end
    end

    def create
        @tip = Tip.new(tip_params)
        if @tip.save
            redirect_to @tip
        else
            render 'new'
        end
    end

    def destroy
        if !login_chk 
            return
        end
        @tip = Tip.find(params[:id])
        @tip.destroy
        redirect_to root_path
    end

    def edit
        if !login_chk 
            return
        end
        @tip = Tip.find(params[:id])
        render 'edit'
    end

    def update
        if !login_chk 
            return
        end
        @tip = Tip.find(params[:id])
        if @tip.update(tip_params)
            redirect_to tip_path
        else
            render 'edit'
        end
    end

    private
        def getBaseInfo
            @user = current_user
            @pageNumber = params[:page] || 1
            @categories = Category.all
        end

        def tip_params
            params.require(:tip).permit(:title, :category_id, :contents, :user_id)
        end

end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/edit.html.erb
<div class="uk-width-1-1 new-tip">
    <h2 class="uk-width-1-1 new-tip-title">EDIT Tip...</h2>
    <div class="uk-width-1-1 new-tip-form">
        <% @tip.errors.full_messages.each do |message| %>
            <%= content_tag(:div, message, class: "uk-alert uk-alert-danger") %>
        <% end %>

        <%= form_for(@tip, url: tip_path) do |f| %>
            <div class="uk-margin-top">
                <%= f.label :Title, class: 'yi-title' %><br>
                <%= f.text_field :title, class: 'yi-input2' %>
            </div>

            <div class="uk-margin-top">
                <%= f.label :Category, class: 'yi-title' %><br>
                <%= f.collection_select(:category_id, @categories, :id, :name, {}, {:class => "yi-select"}) %>
            </div>

            <div class="uk-margin-top">
                <%= f.label :source, class: 'yi-title' %><br>
                <%= f.text_area :contents, {:size => "80x20" , class: 'yi-text-area'} %>
            </div>

            <%= f.hidden_field(:user_id, :value => @user.id) %>

            <%= f.submit "UPDATE TIP", class: "uk-button uk-button-primary uk-button-large uk-margin-top" %>
        <% end %>
    </div>
</div>

app/views/tips/new.html.erb
<div class="uk-width-1-1 new-tip">
    <h2 class="uk-width-1-1 new-tip-title">Make New Tip...</h2>
    <div class="uk-width-1-1 new-tip-form">
        <% @tip.errors.full_messages.each do |message| %>
            <%= content_tag(:div, message, class: "uk-alert uk-alert-danger") %>
        <% end %>

        <%= form_for(@tip) do |f| %>
            <div class="uk-margin-top">
                <%= f.label :Title, class: 'yi-title' %><br>
                <%= f.text_field :title, class: 'yi-input2' %>
            </div>

            <div class="uk-margin-top">
                <%= f.label :Category, class: 'yi-title' %><br>
                <%= f.collection_select(:category_id, @categories, :id, :name, {}, {:class => "yi-select"}) %>
            </div>

            <div class="uk-margin-top">
                <%= f.label :source, class: 'yi-title' %><br>
                <%= f.text_area :contents, {:size => "80x20" , class: 'yi-text-area'} %>
            </div>

            <%= f.hidden_field(:user_id, :value => @user.id) %>

            <%= f.submit "POST NEW TIP", class: "uk-button uk-button-primary uk-button-large uk-margin-top" %>
        <% end %>
    </div>
</div>

app/views/tips/show.html.erb
<div class="uk-width-2-3">
    <h2 class="contents-title">
        <%= @tip.title %>
    </h2>
    <div class="tip-contents">
        <div>
            投稿者：<%= link_to @user.name, user_path(@user) %>
            <% if logged_in? %>
                <% if @current_user.favourite?(@tip) %>
                    <%= link_to "", relationship_path(:id => @tip.id), :method => :DELETE, class: "uk-icon-justify uk-icon-star-o gold-star" %>
                <% else %>
                    <%= link_to "", relationships_path(:id => @tip.id), :method => :post, class: "uk-icon-justify uk-icon-star-o silver-star" %>
                <% end %>
                <% if @tip.writer?(@current_user.id) || @current_user.admin? %>
                    <%= link_to "", tip_path(:id => @tip.id), :method => :DELETE, class: "uk-align-right uk-icon-medium uk-icon-trash", data: {confirm: "本当に削除しますか？"} %>
                    <%= link_to "", edit_tip_path(:id => @tip.id), :method => :GET, class: "uk-align-right uk-icon-medium uk-icon-edit" %>
                <% end %>
            <% end %><br>
            カテゴリー：<%= link_to @tip.category.name, category_path(:name => @tip.category.name, :id => @tip.category.id), :method => :post %><br>
            投稿日：<%= @tip.created_at %>
        </div>
        <div class="uk-margin uk-padding tip-source"><%= @tip.contents %></div>
        <div class="comment-input">
            コメント(140字以内)：<br>
            <% if logged_in? %>
                <%= form_for(:comment, url: comments_path) do |f| %>
                    <%= f.text_area :comment, {:size => "60x8"} %>
                    <%= f.hidden_field(:user_id, :value => @current_user.id) %><br>
                    <%= f.hidden_field(:tip_id, :value => @tip.id) %><br>
                    <%= f.submit "投稿", class: "uk-button uk-button-primary uk-button uk-margin-small-top" %>
                <% end %>
            <% end %>
        </div>
        <% @comments.each do |comment| %>
            <div class="comment-disp">
                <div>
                    <%= link_to comment.user.name, user_path(:id => comment.user.id), :method => :get %>
                    <% if logged_in? && (comment.commenter?(@current_user.id) || @current_user.admin? ) %>
                        <%= link_to "削除", comment_path(:id => comment.id), :method => :DELETE %>
                    <% end %>
                </div>
                <div class="comment-contents"><%= comment.comment %></div>
                <div><%= comment.created_at %></div>
            </div>
        <% end %>
    </div>
</div>
<%= render 'layouts/categoryList' %>