config/routes.rb
Rails.application.routes.draw do


  get 'comments/create'

  root      'static_pages#home'
  post      '/',              to: 'static_pages#home'
  get       'category',       to: 'static_pages#category'
  post      'category',       to: 'static_pages#category'
  get       'login',          to: 'session#new'
  post      'login',          to: 'session#create'
  get       'logout',         to: 'session#destroy'
  get       'mypage',         to: 'mypage#top'
  post      'mypage',         to: 'mypage#top'
  get       'favourites',     to: 'mypage#favourites'
  post      'favourites',     to: 'mypage#favourites'

  resources :comments
  resources :tips
  resources :users
  resources :relationships,  only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tips
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :tip
    belongs_to :user
    validates :comment, presence: true, length: { maximum: 140 }

    def commenter?(user_id)
        user.id == user_id
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :favourite_tip, class_name: "Tip"
    belongs_to :favouritter,   class_name: "User"
    validates :favourite_tip_id, presence: true
    validates :favouritter,      presence: true
end

app/models/tip.rb
class Tip < ApplicationRecord
    include SessionHelper
    
    has_many :passive_relationships, class_name:  "Relationship",
                                     foreign_key: "favourite_tip_id",
                                     dependent:   :destroy

    has_many :favouritter, through: :passive_relationships, source: :favouritter
    has_many :comments, dependent: :destroy

    belongs_to :category
    belongs_to :user

    validates :title        ,presence: true
    validates :category_id  ,presence: true
    validates :contents     ,presence: true ,length: { maximum: 1500 }

    def writer?(user_id)
        user.id == user_id
    end
end

app/models/user.rb
class User < ApplicationRecord
    include SessionHelper
    has_many  :active_relationships, class_name:  "Relationship",
                                     foreign_key: "favouritter_id",
                                     dependent:   :destroy
    
    has_many  :favourite_tip, through: :active_relationships, source: :favourite_tip

    has_many  :tips
    validates :name, presence: true, length: { maximum: 20 }, uniqueness: true

    has_many  :comments, dependent: :destroy

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def favourite(favourite_tip)
        active_relationships.create(favourite_tip_id: favourite_tip.id, favouritter_id: id)
    end

    def unfavourite(favourite_tip)
        active_relationships.find_by(favourite_tip_id: favourite_tip.id, favouritter_id: id).destroy
    end

    def favourite?(tip)
        favourite_tip.include?(tip)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionHelper
    
    def getBaseInfo
        @user = current_user
        @pageNumber = params[:page] || 1
        @categories = Category.all
    end

    def getBaseInfo2
        @user = current_user
        @pageNumber = params[:page] || 1
    end

    def pagenate (buf, method)
        @count = buf.count
        @tips = Kaminari.paginate_array(buf).page(@pageNumber).per(10)
        @method = method
    end

    def login_chk
        if !logged_in?
            redirect_to '/login'
            return false
        end
        return true
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
      if !login_chk 
            return
      end
      @comment = Comment.new(comment_params)
      if @comment.save
        redirect_to @tip
      else
        redirect_to @tip
      end
  end

  def destroy
      if !login_chk 
            return
      end
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to request.referer
  end

  private
    def comment_params
        @tip = Tip.find_by(id: params[:comment][:tip_id])
        params.require(:comment).permit(:comment, :user_id, :tip_id)
    end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

    before_action :getBaseInfo2

    def top
        if !login_chk 
            return
        end
        pagenate(Tip.where(user_id: @user.id).order("updated_at desc"), "post")
    end

    def favourites
        if !login_chk 
            return
        end
        pagenate(@user.favourite_tip.order("updated_at desc"), "post")
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new 
    end

    def create
        user = User.find_by(name: params[:session][:name].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to mypage_path
        else
            flash[:danger] = 'Invalid name/password combination'
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
    end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController

    before_action :getBaseInfo

    def show
        @tip = Tip.find(params[:id])
        @current_user = current_user
        @user = User.find_by(id: @tip.user_id)
        @comments = @tip.comments.order("updated_at desc")
    end

    def new
        @tip = Tip.new
        if logged_in?
            render 'new'
        else
            redirect_to '/login'
        end
    end

    def create
        @tip = Tip.new(tip_params)
        if @tip.save
            redirect_to @tip
        else
            render 'new'
        end
    end

    def destroy
        if !login_chk 
            return
        end
        @tip = Tip.find(params[:id])
        @tip.destroy
        redirect_to root_path
    end

    def edit
        if !login_chk 
            return
        end
        @tip = Tip.find(params[:id])
        render 'edit'
    end

    def update
        if !login_chk 
            return
        end
        @tip = Tip.find(params[:id])
        if @tip.update(tip_params)
            redirect_to tip_path
        else
            render 'edit'
        end
    end

    private
        def getBaseInfo
            @user = current_user
            @pageNumber = params[:page] || 1
            @categories = Category.all
        end

        def tip_params
            params.require(:tip).permit(:title, :category_id, :contents, :user_id)
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    before_action :getBaseInfo2


    def new 
        @user = User.new
    end


    def show
        @user = User.find_by(id: params[:id])
        pagenate(Tip.where(user_id: @user.id).order("updated_at desc"), "get")
    end


    def edit
        if !login_chk 
            return
        end
        @user = User.find_by(id: params[:id])
    end


    def update
        if !login_chk 
            return
        end
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            puts "OK"
            redirect_to mypage_path
        else
            puts "NG"
            render 'edit'
        end
    end


    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to mypage_path
        else
            render 'new'
        end
    end


    def destroy
        if !login_chk 
            return
        end
        User.find(params[:id]).destroy
        log_out
        redirect_to root_url
    end


    private
        def user_params
            params.require(:user).permit(:id, :name, :password, :password_confirmation, :giturl)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/session_helper.rb
module SessionHelper
    
    def log_in (user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_categoryList.html.erb
<div class="uk-width-1-3">
    <h2 class="contents-title2">Topics</h2>
    <div class="topics uk-grid">
        <% @categories.each do |category| %>
            <div class="topic uk-width-1-2">
                <%= link_to category.name, category_path(:name => category.name, :id => category.id), :method => :post %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div>@ProgramingTips, Made by 
        <a href="https://github.com/Yu-s">Yu-s</a>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="uk-navbar uk-margin header">
    <%= link_to "ProgramingTips", root_path, id: "logo" %>
    <div class="uk-align-right" data-uk-dropdown="{mode:'click'}" style="position:relative; margin:10px;" >
        <% if logged_in? %>
        <div><a class="uk-navbar-toggle" uk-navbar-toggle-icon href="#" style="font-size:2em;"></a></div>
        <div class="uk-dropdown uk-dropdown-small" style="background-color:white;border-radius:5px;border-style:solid; border-color:coral;">
            <ul class="uk-nav uk-nav-dropdown">
                <li><%= link_to  "マイページ", mypage_path %></li>
                <li><%= link_to  "投稿する", new_tip_path %></li>
                <li><%= link_to  "お気に入り", favourites_path %></li>
                <li><%= link_to  "ログアウト", logout_path %></li>
            </ul>
        </div>
        <% else %>
            <%= link_to "Login", login_path, id: "login", class: "uk-button uk-button-default" %>
        <% end %>
    </div>
</nav>

app/views/layouts/_pagenate.html.erb
<div class="prog-bar uk-width-1-1">
    <%= link_to_prev_page @tips, 'BACK', class:'uk-align-left', :method => @method %>
    <h><%= page_entries_info(@tips) %></h>
    <%= link_to_next_page @tips, 'NEXT', class:'uk-align-right', :method => @method  %>
</div>

app/views/layouts/_tip.html.erb
<% @tips.each do |tip| %>
    <div class="tip" style="font-size:1.3em;">
        <div><%= link_to tip.title, tip_path(tip), class: "toTipContents" %></div>
        <div>
            <%= link_to tip.category.name, category_path(:name => tip.category.name, :id => tip.category.id), :method => :post %>
            <%= link_to tip.user.name, user_path(:id => tip.user.id), :method => :get %>
            <span><%= tip.updated_at.strftime("%Y/%m/%d %H:%M") %></span>
            <% if logged_in? %>
                <% if current_user.favourite?(tip) %>
                    <%= link_to "", relationship_path(:id => tip.id), :method => :DELETE, class: "uk-icon-justify uk-icon-star-o gold-star" %>
                <% else %>
                    <%= link_to "", relationships_path(:id => tip.id), :method => :post, class: "uk-icon-justify uk-icon-star-o silver-star" %>
                <% end %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgramingTips</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main-contents uk-grid">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>